// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// writer is an autogenerated mock type for the writer type
type writer struct {
	mock.Mock
}

// Write provides a mock function with given fields: text
func (_m *writer) Write(text []byte) error {
	ret := _m.Called(text)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(text)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTnewWriter interface {
	mock.TestingT
	Cleanup(func())
}

// newWriter creates a new instance of writer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWriter(t mockConstructorTestingTnewWriter) *writer {
	mock := &writer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
