// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	"github.com/ast3am/wb-test/internal/models"
	"github.com/stretchr/testify/mock"
)

// cache is an autogenerated mock type for the cache type
type cache struct {
	mock.Mock
}

// InsertOrdersToCache provides a mock function with given fields: orders
func (_m *cache) InsertOrdersToCache(orders models.Orders) {
	_m.Called(orders)
}

type mockConstructorTestingTnewCache interface {
	mock.TestingT
	Cleanup(func())
}

// newCache creates a new instance of cache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCache(t mockConstructorTestingTnewCache) *cache {
	mock := &cache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
